### ISSUE TITLE
希望可以区分番剧的状态

### ISSUE THREAD

**Issue by Katou-Kouseki** [KiritaniAyaka/hexo-bangumi-page#1]
例如bgm.tv中的 在看 | 看过 | 想看 | 搁置，四种状态，另外番剧多了一整页下来挺诡异的，能分页吗(

**Comment by KiritaniAyaka** [comment]
状态显示一直有，还是说你指的是别的什么

分页已经完成 [555cb3a](https://github.com/KiritaniAyaka/hexo-bangumi-page/commit/555cb3a70444a9f2f37e4fdb1a222a1fb91c63bb) 用法见 README

**Comment by Katou-Kouseki** [comment]
> 状态显示一直有，还是说你指的是别的什么
> 
> 分页已经完成 [555cb3a](https://github.com/KiritaniAyaka/hexo-bangumi-page/commit/555cb3a70444a9f2f37e4fdb1a222a1fb91c63bb) 用法见 README

就是能不能根据状态进行分页

**Comment by KiritaniAyaka** [comment]
> > 状态显示一直有，还是说你指的是别的什么
> > 分页已经完成 [555cb3a](https://github.com/KiritaniAyaka/hexo-bangumi-page/commit/555cb3a70444a9f2f37e4fdb1a222a1fb91c63bb) 用法见 README
> 
> 就是能不能根据状态进行分页

大概懂了，晚点有空做（

**Comment by Katou-Kouseki** [comment]
> 

好的！大佬辛苦了，样式很好看希望能继续更新！

**Comment by KiritaniAyaka** [comment]
完成了，更新到最新版本并且在 _config.yml 里配置启用即可
